version: 0.0
os: linux
files: 
  - source: /
    destination: /home/ubuntu/hello-flask
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
  AfterInstall:
    - location: scripts/set_permission
      runas: root
    - location: scripts/after_install.sh
      runas: ubuntu